# -----------------------------
# Stage 1 - Build
# -----------------------------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore src/UserService.API/UserService.API.csproj

RUN dotnet publish src/UserService.API/UserService.API.csproj \
    -c Release \
    -o /app/publish

# -----------------------------
# Stage 2 - Runtime
# -----------------------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

ENTRYPOINT ["dotnet","UserService.API.dll"]