services:

  postgres:
    image: postgres:16

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    networks:
      - devops-network


  userservice:
    image: userservice:v1

    container_name: userservice

    depends_on:
      - postgres

    ports:
      - "2003:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

    networks:
      - devops-network

  productservice:
    image: productservice:v1

    container_name: productservice

    depends_on:
      - postgres

    ports:
      - "2004:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

    networks:
      - devops-network
      

volumes:
  postgres_data:

networks:
  devops-network: