name: OrderService CI

on:
  push:
    branches:
      - main
    paths:
      - 'services/OrderService/**'
      - '.github/workflows/ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/OrderService

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/orderservice

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore OrderService.sln

      - name: Build
        run: dotnet build OrderService.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test OrderService.sln --configuration Release --no-build

      # - name: Run OWASP Dependency-Check
      #   run: |
      #     mkdir -p reports

      #     docker run --rm \
      #     -v ${{ github.workspace }}:/src \
      #     -v ${{ github.workspace }}/reports:/report \
      #     owasp/dependency-check:latest \
      #     --nvdApiKey ${{ secrets.NVD_API_KEY }} \
      #     --scan /src/services/OrderService \
      #     --project OrderService \
      #     --format HTML \
      #     --out /report

      # - name: Upload Dependency Check Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dependency-check-report
      #     path: reports

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Short SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
          -t $IMAGE_NAME:$IMAGE_TAG \
          .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          ignore-unfixed: true
          exit-code: 1
          vuln-type: library
          severity: CRITICAL,HIGH

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM
        run: |
          syft \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -o cyclonedx-json=sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: orderservice-sbom
          path: sbom.json


      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker Image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          echo "$COSIGN_PRIVATE_KEY" > cosign.key

          cosign sign \
            --key cosign.key \
            --yes \
            $IMAGE_NAME:$IMAGE_TAG